version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/rindoku
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/rindoku
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /rindoku
    depends_on:
      - app